export const CHANGE_INPUT = "CHANGE_INPUT";
export const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";

//-------Sign up-------------
export const SUBMIT_FORM = "SUBMIT_FORM";
export const SUBMIT_FORM_SUCCESS = "SUBMIT_FORM_SUCCESS";
export const SUBMIT_FORM_FAILURE = "SUBMIT_FORM_FAILURE";

export const GET_USERS = "GET_USERS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILURE = "GET_USERS_FAILURE";

export const LOGIN_FORM = "LOGIN_FORM";
export const LOGIN_FORM_SUCCESS = "LOGIN_FORM_SUCCESS";
export const LOGIN_FORM_FAILURE = "LOGIN_FORM_FAILURE";

export const LOGOUT = "LOGOUT";
